### ISSUE TITLE
EPIC: Well data

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#501]
# Export of well data from FMU workflows

_As agreed offline 6 march 2024 (fmu-dataio, Webviz, Sumo), this is a description of an Epic on supporting the export of wells and well data from FMU workflows. While this is currently possible, and while there is some support for well data in fmu-dataio already, the topic is far from "Done"._

## Introduction and context
Wells and well data are central data types in all FMU workflows, and they are frequently part of exported results. Examples of use cases for exported well data include QC and visualization.

Well data may be static (imported from other sources, used unmodified through the workflow), modified (imported, modified for modeling purposes) or created (e.g. sampled from 3D grid parameters, etc) within FMU.

### Master data definitions
Drilled wells are defined by masterdata in SMDA, and each well (or wellbore?) is identified via a UUID. SMDA, for wells, also contain regular data (well paths).

Within FMU, there is currently no "master data" defined. E.g. while the same wells are used in multiple components, the reference between them is usually their name. The name is frequently not the same in different software, e.g. the name used in RMS is not the same as the name used in Eclipse. The need for having (global) definitions of individual wells comes up frequently when discussing these issues. This may or may not be part of this Epic.

_Note that the concept of master data is tricky in Drogon, as it does not exist, and is thus not defined in any master data._

### Import
Well data are imported to FMU from various sources, including established data bases or (manually or automated) from other applications. It is common that well paths come from one source, while well logs come from different sources. Example: Well path from OpenWorks, petrophysical well logs from Geolog and facies logs from IC. Logs can also come from arbitrary sources, including Excel sheets, txt-files, etc. This Epic does not include the _import_ context, only export and associated FMU metadata populated onto exported data. However, when discussing master data and references to global identifiers etc, it is likely to look towards the import mechanisms for retaining existing references. However, given the chaotic picture described above, this is probably - at this point - not possible.

## Terminology
From https://www.sodir.no/fakta/bronner/klassifisering-av-bronner/

> Definitions
>Well: borehole which is drilled in order to discover or delimit a petroleum deposit and/ or to produce petroleum or water for injection purposes, to inject gas, water or other medium, or to map or monitor well parameters. There are several categories of wells. A well may consist of one or several wellbores (well paths) and may have one or several termination points.
Wellbore (well path): designates the location of the well from one termination point to the wellhead. A wellbore may consist of one or more well tracks.
Well track: the part of a wellbore (well path) which extends from a point of drilling out on the existing wellbore (kick-off point) to a new termination point for the well.
Multilateral wellbore: has more than one wellbore radiating from the main wellbore. In contrast to sidetracked wells where the first bottom section is plugged back before a sidetrack is drilled, multilateral wellbores have more than one wellbore open at the same time.
Other wellbore: SOIL DRILLING (drilling in connection with subsurface surveys to investigate the soil conditions prior to placement of facilities), SHALLOW GAS (drilling to investigate shallow gas before the first 'real' drilling on the location), PILOT (drilling to investigate the geology and fluid contacts for location of the main wellbore), SCIENTIFIC (drilling according to Act relating to Scientific research and
exploration), STRATIGRAPHIC (drilling according to Act relating to Petroleum activities
§2-1).

Note! This terminology may differ from that conventionally used in various software.

### Well types* and categories
Common well _types_ used in FMU workflows include _producers_ (wells that produce oil or gas), _injectors_ (wells that inject water or gas), _exploration/appraisal wells_ (wells drilled for information or data), _observation wells_ (wells used for monitoring) and others.

Wells in FMU come in several categories, including _drilled_ wells (well data representing a real well or wellbore), _planned wells_ (well data representing wells in (various stages of) the planning phase, "_dummy wells_" (mock wells that are inserted into e.g. RMS to force certain behavior of the software).

*) The use of words such as "type" and "category" may not be accurate and may be subject to change.

### Well _data_
A wellbore has a wellpath represented (usually) by coordinates, however this may vary depending on format. In addition, wells are frequently associated with data (logs). Logs can be _continuous_ or _discrete_ and represent measurement, calculations or classifications along the wellbore. (Very similar to a time series, only with depth as the scale). _Depth_ can be in MD (measured depth) (along the wellbore) or other (calculated) depth measurements including TVD (True Vertical Depth), TST (True Stratigraphic Depth), etc. 

### Blocked wells
When well data is used in 3D grids, they are upscaled from log scale to grid scale. Essentially populating the penetrated cells of the grid with values representing the part of the wellbore that transects the cell. This _blocked well_ is used further in the modeling process for distributing parameters in 3D.

## Definition of Done
This Epic is complete when the following conditions are met:
- A data model for well data _when exported out of FMU workflows_ is defined, including:
  - A functioning data format, and
  - Context (metadata) meeting the following requirements:
    - Sufficient for unambiguous data identification (always possible to filter down to one specific object)
    - Producible in FMU workflows (can be fully automated, in a sustainable way)
    - Minimum end-user configuration needed
    - Scalable (no irreversible choices or dead-ends)
    - Following existing conventions in the data model and fmu-dataio whenever possible
- Export and data model for wells are documented, also understandable outside FMU context
- Well data are exported out of FMU workflows in a consistent way using `fmu-dataio`
- Solution is implemented in Drogon, meeting the following requirements
  - Implementation is intuitive and follow current conventions
- Solution iterated with real FMU setups, and preferably tested in the wild.
- If applicable, well data exported from FMU are mappable to OSDU standards.

## Dependencies
XTgeo? SMDA?

## Refinement of this Epic
- [ ] Refine and describe this Epic
  - [ ] Agree on and describe definition of Done
  - [ ] Agree on and describe requirements
  - [ ] Agree on and describe scope for first iteration (MVP), including use cases
  - [ ] Create and describe subtasks (ideally a minimum amount, but avoiding open-ended tasks)
- [ ] Review any existing definitions of well data used in OSDU, for alignment
- [ ] Define scope of "well" in FMU (e.g. is blocked wells included or not)

## Suggested Minimum Viable solution:
- [ ] [Basic support for export of wells in fmu-dataio](https://github.com/equinor/fmu-dataio/issues/318)

## Beyond MVP:
- [ ] [Support blocked wells ](https://github.com/equinor/fmu-dataio/issues/372)
- [ ] Global definitions of wells within an FMU setup
- [ ] Add masterdata reference to metadata

-----------------

_Existing tasks to be repurposed or closed:_
https://github.com/equinor/fmu-dataio/issues/267
