### ISSUE TITLE
Add `export_fault_lines()` one liner export

### ISSUE THREAD

**Issue by mferrera** [equinor/fmu-dataio#763]
Currently fault polygons are exported from RMS projects in the following way:

- Specify the horizon names
- Specify a folder, under the assumption this folder exists for each horizon
- Loop through each horizon, and if that folder is there and not empty,
  - Create an `xtgeo.Polygon` from the RMS polygon
  - Create an `ExportData` instance for each file format being exported
  - Set the polygon fileformat
  - Export

## Simplification

A possible one-liner export could instead look something like this:

```python
for category_name in HORIZON_NAMES:
    export_fault_lines(
        project: Any, 
        category_name: str,
        vertical_domain: str = "depth",  # or "time"
        config_path: str | Path = "../../fmuconfig/output/global_variables.yml",
        classification: str | None = None, # Actual default from config
    )
```

This means we will provide defaults for `tagname`, `name`, and `workflow` (and anything else not listed). This provides a good substrate to accomplish standardization and guide assets to conforming to a single way of doing it, while also allowing an escape hatch of using `ExportData` directly to deviate from them.

## TODO

- How should we structure the aforementioned defaulted values (tagname, name, workflow)?

## Tasks
- [ ] Implement the function
- [ ] Update documentation and examples
  - [ ] https://fmu-dataio.readthedocs.io/en/latest/examples.html#exporting-fault-polygons

**Comment by mferrera** [comment]
Consider naming this `fault_lines` over `fault_polygons` to prefer the data _product_ over the data _type_.

**Comment by mferrera** [comment]
Sept 25 2024 - updated root comment with refinement from discussions and removing the list of unanswered questions as we have now mostly answered them. This is now approaching "final".

**Comment by tnatt** [comment]
I am currently working on the PR for exporting `fault_lines`, and there is now a need to align on the export format for these polygons. 

1. Do we still want polygons to be stored as `csv,` or would we prefer `parquet` here as well like we did for the `inplace_volumes?`
2. And should we keep the `XTGeo` column names `X,_UTME, Y_UTMN, Z_TVDSS, POLY_ID` or do we prefer  `X, Y, Z, ID`. 



I would prefer that all polygons exported using fmu-dataio have the same naming and format ref #1058 . Now consumers have to deal with both naming conventions. 
- Example in the `webviz` code: https://github.com/equinor/webviz/blob/274dacec6d91c9c1388096b0da7f542e7a582038/backend_py/primary/primary/services/sumo_access/polygons_access.py#L70-L79
- Example in the REP code: https://github.com/equinor/REP/blob/f0283844c1e37dd3aa38b2a06a63754145da7024/Databricks/REPDBricks/Corporate/SUMO/Transformation/functions/read_polygon_file.py#L21-L25

Any strong opinions on this? @perolavsvendsen @mferrera @jcrivenaes @rwiker . Have this been discussed in the past?

**Comment by perolavsvendsen** [comment]
✅ Some opinions
✅ Has been discussed in the past 😁 

(I think all those discussion were in Team DM's which means they are lost forever now)

My vote is:

- Stick to `csv` file format
- Stick to generic (`X`, `Y` etc) headers

...because it feels like the least painful way. I think this would give seamless transition.

But...

Changing to `parquet` is in the "why not?" category, and makes some sense to me. It will require coordination and e.g. REP will probably then have to create another fallback to csv if parquet is not available. (Some fields will insist on using old Komodo versions for a long time, so the process will take at least 6 months, probably.) The upside would be transfer speed, storage space. But then again, these are typically quite small files? So perhaps not worth the change management??

As for headers, I'm pretty sure we have converged on the more generic version (`X`, `Y` etc) many times. My vote is for continuing to do that. The REP code that falls back to XTgeo headers must be at least 7 years old legacy.

--------------

The only great argument for changing I can think of would be if there are well established and known other standards out there that we should rather use. I don't think this is super important inside of FMU, and we can always (...) translate to other formats if need be (ref OSDU discussion). But if super-efficient and nice and open formats do exist and would be easy to use, then perhaps that would be worth looking into. But I don't really think so 🤷‍♂

**Comment by perolavsvendsen** [comment]
I see no _very_ good reasons for _not_ moving to parquet (in the future) 🤷‍♂ And I also agree with the logic of just doing it now. Not 100% sure of the consequences:

**Data consumers**
Data consumers need to change, and probably also be robust for both parquet and csv in a transition period. Probably also doable. We need to clearly inform them, since we are changing a thing for which we have "contracts" to others. We definitely need to talk to REP. (Perhaps we bundle a few of these changes and have another meeting with them. We can probably also given them quite direct hints on what they should put into their code to make it robust for the old and the new.)

**Existing results**
This is probably where changing format hurts the most. For identical files, it is "easy" to retrofit to legacy results. Somewhat more complicated if the data also has to be changed. We probably have to do this, because some of the historical cases in Sumo are going to be reference cases for a long time. I.e. Webviz will want to show them, etc.

**Models, post-processing and local visualization/integration**
There might be some local scripts etc requiring updates. May or may not be a large job, but my gut feeling is that this is doable.

**End users**
I'm not very worried about the end user aspect here, but others have to calibrate that assumption. (Those working with Python will probably adapt quickly. The double-clickers are most likely never opening fault lines in e.g. Excel or Notepad or whatever.)

**Comment by tnatt** [comment]
Side note, we should add the fault name to the exported table once this is supported in xtgeo https://github.com/equinor/xtgeo/issues/900
